version: '3.5'
services:
  gc-ui-react-ts:
    container_name: gc-ui-react-ts
    build:
      context: ../ui-react-ts
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      REACT_APP_API_BASE_URL: http://localhost:18080
    stdin_open: true
