version: '3.5'
services:

  geeksclub-db:
    image: postgres:12.3
    container_name: geeksclub-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - PGDATA=/data/postgres
      - POSTGRES_MULTIPLE_DATABASES=dev,test
    ports:
      - "15432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  gc-api-springboot:
    build: ../api-springboot
    ports:
      - "18080:8080"
    restart: unless-stopped
    depends_on:
      - geeksclub-db
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
      SPRING_DATASOURCE_URL: jdbc:postgresql://geeksclub-db:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    healthcheck:
      test: "java /app/HealthCheck.java || exit 1"
      interval: 20s
      timeout: 5s
      retries: 5
      start_period: 40s
    volumes:
      - ./HealthCheck.java:/app/HealthCheck.java
  gc-ui-react:
    container_name: gc-ui-react
    build:
      context: ../ui-react
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      REACT_APP_API_BASE_URL: http://localhost:18080
    stdin_open: true
